### ISSUE TITLE
Task: dynamic shopping cart

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/techcycle#14]
Update the shopping cart display and functionality.

**Tasks**
- [ ] Design and implement the visual representation of the shopping cart.
- [ ] Implement logic to calculate the subtotal and total amount in the shopping cart.
- [ ] Add functionality to adjust quantities and remove items from the shopping cart.
