### ISSUE TITLE
Task: display products with special offers

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/techcycle#16]
Design and implement a dedicated section on the homepage for displaying deals, clearance items, and special offers.

**Tasks**
- [ ] Design the layout and structure of the dedicated section.
- [ ] Implement logic to fetch and filter the relevant products.
- [ ] Display the retrieved products in the dedicated section.
