### ISSUE TITLE
Task: visual cues

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/techcycle#17]
Apply visual cues and labels to differentiate the discounted items.

**Tasks**
- [x] Design visual cues to indicate discounted items.
- [x] Implement logic to identify and flag discounted items.
- [x] Display the visual cues on the relevant product elements.
