### ISSUE TITLE
Task: shopping cart

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/techcycle#18]
Design and create the shopping cart page layout and structure.

**Tasks**
- [x] Plan the layout and structure of the shopping cart page.
- [x] Design the visual presentation of the shopping cart page.
- [x] Implement the layout and structure in HTML and CSS.
