### ISSUE TITLE
Task: calculate price

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/techcycle#19]
Implement the logic to calculate and display the total amount.

**Tasks**
- [x] Retrieve the product prices and quantities.
- [x] Calculate the subtotal for each product.
- [x] Sum up the subtotals to calculate the total amount.
