### ISSUE TITLE
Task: update price

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/techcycle#20]
Ensure the real-time update of the total amount.

**Tasks**
- [x] Implement event listeners for quantity changes.
- [x] Update the subtotals when quantities change.
- [x] Recalculate and display the total amount.
