### ISSUE TITLE
Task: registration validation and enhancement

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/techcycle#23]
Design and implement the registration form UI, including the necessary input fields and validation.

**Tasks**
- [x] Design the Registration Form UI
- [x] Implement Input Fields and Validation
- [x] Enhance User Experience
