### ISSUE TITLE
Task: email verification

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/techcycle#24]
As a **role** I can **capability** so that **received benefit**.

**Acceptance Criteria**
- 1
- 2
- 3

**Tasks**
- [ ] Choose a Transactional Email Service
- [ ] Configure the Transactional Email Service
- [ ] Implement Email Sending Functionality
