### ISSUE TITLE
Task: shopping cart backend

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/techcycle#30]
Implement Shopping Cart Backend

**Tasks**
- [x] Create views and url to handle the shopping cart functionality.
- [x] Fetch and display the products in the cart from the database.
- [ ] Implement functionality to update the quantity of products and remove items from the shopping cart.

**Comment by GaborFicsor** [comment]
Buttons for updating the quantity of each product will be implemented at a later stage.
