### ISSUE TITLE
Task: clear cart

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/techcycle#31]
Implement Clear Cart Functionality

**Tasks**
- [ ] Add a "Clear Cart" button or link to allow shoppers to remove all items from the cart at once.
- [ ] Implement the logic to handle the clearing of the shopping cart, including updating the cart's total price.
- [ ] Provide success message to the shopper after clearing the cart.

**Comment by GaborFicsor** [comment]
A clear cart button will be implemented at a later stage
