### ISSUE TITLE
Task: checkout backend 

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/techcycle#34]
Implement Checkout Backend

**Tasks**
- [x] Create Django views and urls to handle the checkout process.
- [x] Write the necessary logic to retrieve the selected products and calculate the total price.
- [x] Implement functionality to capture and validate the shipping information and payment details.
