### ISSUE TITLE
Task: confirmation email

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/techcycle#37]
Create confirmation Email

**Tasks**
- [x] Design email template for the order confirmation.
- [x] Include relevant branding elements.
- [x] Create the content for the order confirmation email, including the necessary order details.
- [x] Include information such as the order number, purchased items, quantities, total amount, shipping address.
