### ISSUE TITLE
Task: contact form

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/techcycle#42]
Implement the Contact Form

**Tasks**
- [ ] Design contact form with validation and fields such as name, email, subject, and message.
- [ ] Implement the server-side logic to handle form submissions when the user submits the contact form.
- [ ] Configure confirmation email
