### ISSUE TITLE
Task: searching and filtering

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/techcycle#6]
The products should be categorized or tagged appropriately to facilitate easy browsing and filtering.

The website should have a search functionality that allows me to search for specific products based on keywords, categories, or other relevant criteria.

**Tasks**
- [x] Categorize or tag the products in the database and create filters to allow users to browse products by category or tag.
- [x] Create a search form and UI component.
- [x] Implement the backend search functionality
- [x] Display search results
